### ISSUE TITLE
Mod cannot run on dedicated servers due to unavailable dependency

### ISSUE THREAD

**Issue by HexFlareheart** [MtcLeo05/Sanguine-Neural-Networks#1]
Attempting to load this mod on a dedicated server throws a somehow non-fatal fatal error (IE the program halts but doesn't crash out) of `java.lang.NoClassDefFoundError: com/ibm/icu/impl/Pair`. This occurs due to the fact that the library this class comes from, `icu4j`, isn't installed on dedicated servers; there is no easy way to fix this on the end-user's end. Believe me, I tried.

I don't readily have a solution to this problem besides not depending on a client-only library; however I HAVE seen [another mod](https://github.com/lightning2401/northstar/pull/40) have this problem, and while the solution presented for it (which depends on Create, which the mod in question is an add-on for) isn't applicable here, it may be useful information?

Also, I'd recommend changing the internal name you're using to something more descriptive. Troubleshooting this problem took an entire order of magnitude longer than necessary because I didn't know what `snn` was referring to in the log, couldn't find anything on it through the power of "just google it", assumed it was something internal and Java just straight-up wasn't telling me what the problem was, and moved on to other troubleshooting steps. I didn't even realize it was Sanguine Neural Networks until I was going through disabling mods to troubleshoot and disabled Hostile Neural Networks without disabling Sanguine Neural Networks, saw it pull the internal name when it inevitably complained, and finally understood where the problem was coming from.

**Comment by MtcLeo05** [comment]
Thanks for the report!
I'm currently investiganting for the server problem, hopefully I'm able to find a fix.

For the internal name matter, on one hand I agree but on the other changing it now would probably cause issues with existing worlds, I'll see what I can do to fix it.
